In [1]:
import pandas as pd
from src.utils.stat_analysis.stat_utils import stars_to_p

### Diff

In [2]:
resolution = 'sentence'
df = pd.read_csv(f'/data/home/gkeren/Readability/src/Correlations/L1_and_L2/FirstReading/ppl_comp_res_{resolution}.csv')
df['ppl_coef_p_category'] = df['ppl_coef_p_symbol'].apply(stars_to_p)
diff_df = df[df['level_type']=='diff']
cols = ['level_type', 'pred_col', 'ppl_coef', 'ppl_coef_p', 'ppl_coef_p_category', 'ppl_coef_p_symbol', 'n_values']
diff_df[cols]

,level_type,pred_col,ppl_coef,ppl_coef_p,ppl_coef_p_category,ppl_coef_p_symbol,n_values
1,diff,mean_nonzero_TF,0.002672,5.735305e-08,p < 0.001,***,32
3,diff,SkipRateTotal,0.000988,2.329028e-06,p < 0.001,***,32
5,diff,RegRateTotal,0.000063,7.597550e-01,p > 0.05,ns,32

In [3]:
resolution = 'paragraph'
df = pd.read_csv(f'/data/home/gkeren/Readability/src/Correlations/L1_and_L2/FirstReading/ppl_comp_res_{resolution}.csv')
df['ppl_coef_p_category'] = df['ppl_coef_p_symbol'].apply(stars_to_p)
diff_df = df[df['level_type']=='diff']
cols = ['level_type', 'pred_col', 'ppl_coef', 'ppl_coef_p', 'ppl_coef_p_category', 'ppl_coef_p_symbol', 'n_values']
diff_df[cols]

,level_type,pred_col,ppl_coef,ppl_coef_p,ppl_coef_p_category,ppl_coef_p_symbol,n_values
1,diff,mean_nonzero_TF,0.002775,0.000011,p < 0.001,***,32
3,diff,SkipRateTotal,0.002359,0.000036,p < 0.001,***,32
5,diff,RegRateTotal,-0.000013,0.978946,p > 0.05,ns,32

### all levels, not diff

In [4]:
resolution = 'sentence'
df = pd.read_csv(f'/data/home/gkeren/Readability/src/Correlations/L1_and_L2/FirstReading/ppl_comp_res_{resolution}.csv')
df['ppl_coef_p_category'] = df['ppl_coef_p_symbol'].apply(stars_to_p)
all_df = df[df['level_type']!='diff']
cols = ['level_type', 'pred_col', 'ppl_coef', 'ppl_coef_p', 'ppl_coef_p_category', 'ppl_coef_p_symbol', 'n_values']
all_df[cols]

,level_type,pred_col,ppl_coef,ppl_coef_p,ppl_coef_p_category,ppl_coef_p_symbol,n_values
0,all,mean_nonzero_TF,0.006235,1.264835e-08,p < 0.001,***,32
2,all,SkipRateTotal,0.003993,3.703781e-09,p < 0.001,***,32
4,all,RegRateTotal,0.002358,1.676039e-07,p < 0.001,***,32

In [5]:
resolution = 'paragraph'
df = pd.read_csv(f'/data/home/gkeren/Readability/src/Correlations/L1_and_L2/FirstReading/ppl_comp_res_{resolution}.csv')
df['ppl_coef_p_category'] = df['ppl_coef_p_symbol'].apply(stars_to_p)
all_df = df[df['level_type']!='diff']
cols = ['level_type', 'pred_col', 'ppl_coef', 'ppl_coef_p', 'ppl_coef_p_category', 'ppl_coef_p_symbol', 'n_values']
all_df[cols]

,level_type,pred_col,ppl_coef,ppl_coef_p,ppl_coef_p_category,ppl_coef_p_symbol,n_values
0,all,mean_nonzero_TF,0.006107,1.115252e-08,p < 0.001,***,32
2,all,SkipRateTotal,0.002752,2.944781e-07,p < 0.001,***,32
4,all,RegRateTotal,0.003540,1.523660e-07,p < 0.001,***,32